platform :ios, '8.0'

target 'ChatDemo' do

    pod 'Hyphenate', :inhibit_warnings => true

    pod 'SDWebImage'
    
    #pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end
